spring:
  redis:
#    host: 127.0.0.1
    password: gingko
#    port: 6380
    pool:
      max-idle: 200
      min-idle: 0
      max-active: 500
      max-wait: 1500
    timeout: 0
    sentinel:
      master: master
      nodes: 127.0.0.1:26380,127.0.0.1:26381,127.0.0.1:26382 # nodes间不能有空格